import type { Metadata } from "next";
import { Besley } from "next/font/google";
import "./globals.css";
import Provider from "./provider";

const besley = Besley({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dwell Interior",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body className={besley.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
